import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Tab from "@/components/Tab";
import { ClientProviders } from "@/components/ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function rootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row m-3">
          <a href="https://www.turbify.com" aria-label="Turbify">
            <Image
              src="https://sep.turbifycdn.com/nrp/image/turbify/newturbifylogo.png"
              alt="Turbify"
              width={100}
              height={40}
              className="shrink-0 h-10 w-auto object-contain"
            />
          </a>
          <Tab />
        </div>
        <ClientProviders> {children}</ClientProviders>
      </body>
    </html>
  );
}
